name: Bug report
description: Create a report to help us improve existing features
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched [open AngaraDAV issues](https://github.com/offsyanka99/AngaraDAV/issues) for this problem.
          required: true
        - label: I have also searched [closed AngaraDAV issues](https://github.com/offsyanka99/AngaraDAV/issues?q=is%3Aissue+is%3Aclosed).
          required: true
        - label: I will describe the problem with as much detail as possible.
          required: true
  - type: input
    id: version
    attributes:
      label: AngaraDAV version or image tag
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: php_version
    attributes:
      label: PHP version
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Give a step-by-step instruction what you have to do before the bug occurrs.
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: After following the steps, what did you expect AngaraDAV to do?
  - type: textarea
    id: current
    attributes:
      label: Current behaviour
      description: What did AngaraDAV do instead?
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Especially in case of a blank page or other larger problems, enable logs on your server and post the error message.
